### ISSUE TITLE
standard zcode support?

### ISSUE THREAD

**Issue by cucca** [bonafid3/zcode2gcode#1]
Hi, i've tryed to convert a M200 zcode created with zsuite v.2.12.0.0, without luck (no output file created and no error messages)! Does it actually support only the zcodex?

**Comment by bonafid3** [comment]
Sure, just rename zcodex file to "something.zip", and extract "ZCodeData" file.
That is the file contains the actual code. I was too lazy to add zip support to my application, but I will do it when I will have time.

**Comment by cucca** [comment]
> 
> 
> Sure, just rename zcodex file to "something.zip", and extract "ZCodeData" file.
> That is the file contains the actual code. I was too lazy to add zip support to my application, but I will do it when I will have time.

i mean zcode not zcodex... have a look here: https://youtu.be/d9IRFfUi1so it doesn't convert zcode to gcode
